import game as g
import player as pl
import board as b

if __name__ == "__main__":
	# Test Basic Functionality of class Player
	print("Testing Class Player")
	player1 = pl.Player(pl.Piece.X)
	player2 = pl.Player(pl.Piece.O)
	print(player1)
	print(player2)

	# Test Basic Functionality of class Board
	print("Testing Class Board")
	board = b.Board(4, 4)
	print(board)
	board.set_piece(3, 0, player1)
	board.set_piece(1, 2, player1)
	board.set_piece(3, 1, player2)
	board.set_piece(2, 0, player2)
	board.set_piece(2, 2, player2)
	board.set_piece(1, 3, player2)
	print(board.get_surr_row(1, 2))
	print(board.get_surr_col(3, 1))
	print(board.get_diag_left(3, 0))
	print(board.get_diag_right(3, 0))
	print(board.get_diag_right(3, 1))
	print(board.get_diag_left(3, 1))
	print(board)
	board.clear_board()
	print(board)

	# Test Basic Functionality of class Game
	print("Testing Class Game")
	game = g.Game(4, 4, pl.Piece.X, pl.Piece.O)
	# Test Drop Placement Valid
	game.start_game()
	game.set_piece(3, 0)
	game.set_piece(3, 1)
	game.set_piece(2, 0)
	game.set_piece(2, 1)
	game.set_piece(1, 0)
	game.set_piece(1, 1)
	game.set_piece(0, 0)
	game.set_piece(0, 1)
	game.view_board()
	# Test Drop Placement Invalid
	game.start_game()
	game.set_piece(3, 0)
	game.set_piece(3, 1)
	game.set_piece(1, 0)
	game.set_piece(1, 1)
	game.set_piece(0, 0)
	game.set_piece(0, 1)
	game.view_board()
	# Test Horizontal Win
	game.start_game()
	game.set_piece(3, 0)
	game.set_piece(2, 0)
	game.set_piece(3, 1)
	game.set_piece(2, 1)
	game.set_piece(3, 2)
	game.set_piece(2, 2)
	game.set_piece(1, 0)
	game.set_piece(2, 3)
	game.set_piece(0, 0)
	game.set_piece(3, 3)
	game.view_board()
	# # Test Diagonal Left Win
	game.start_game()
	game.set_piece(3, 0)
	game.set_piece(3, 1)
	game.set_piece(2, 1)
	game.set_piece(3, 2)
	game.set_piece(3, 3)
	game.set_piece(2, 2)
	game.set_piece(1, 2)
	game.set_piece(2, 3)
	game.set_piece(2, 0)
	game.set_piece(1, 3)
	game.set_piece(0, 3)
	game.view_board()
	# Test Diagonal Right Win
	game.start_game()
	game.set_piece(3, 3)
	game.set_piece(3, 2)
	game.set_piece(2, 2)
	game.set_piece(3, 1)
	game.set_piece(2, 1)
	game.set_piece(3, 0)
	game.set_piece(1, 1)
	game.set_piece(2, 0)
	game.set_piece(0, 1)
	game.set_piece(1, 0)
	game.set_piece(0, 0)
	game.view_board()

	